const leads = {
  leads: [
    // ── Noviembre 2025 ────────────────────────────────────────────
    { nombre: "Valentina",    apellido: "Rodríguez", email: "v.rodriguez@gmail.com",       telefono: "+598 94 123 456", comentario: "Quisiera saber si tienen el Sandero en azul y si acepta plan de financiación.",              vehiculoNombreMarca: "Renault",  fecha: "2025-11-04" },
    { nombre: "Mateo",        apellido: "García",    email: "mateo.garcia@hotmail.com",     telefono: "+598 99 234 567", comentario: "Me interesa el Nissan Kicks, ¿tiene disponible para test drive?",                         vehiculoNombreMarca: "Nissan",   fecha: "2025-11-11" },
    { nombre: "Lucía",        apellido: "Fernández", email: "luciafernandez@outlook.com",   telefono: "+598 91 345 678", comentario: "Busco un vehículo eléctrico económico, vi el BYD Dolphin en su web.",                    vehiculoNombreMarca: "BYD",      fecha: "2025-11-18" },
    { nombre: "Santiago",     apellido: "López",     email: "slopez92@gmail.com",            telefono: "+598 98 456 789", comentario: "¿Cuál es el precio final del Peugeot 208 con todos los impuestos incluidos?",             vehiculoNombreMarca: "Peugeot",  fecha: "2025-11-25" },

    // ── Diciembre 2025 ────────────────────────────────────────────
    { nombre: "Camila",       apellido: "Martínez",  email: "camimartinez@gmail.com",        telefono: "+598 95 567 890", comentario: "Necesito un SUV familiar para 5 personas, ¿qué modelo de Subaru me recomiendan?",        vehiculoNombreMarca: "Subaru",   fecha: "2025-12-02" },
    { nombre: "Tomás",        apellido: "Pérez",     email: "tomas.perez@yahoo.com",          telefono: "+598 93 678 901", comentario: "Consulto por la Riddara en versión doble cabina. ¿Tienen stock disponible?",             vehiculoNombreMarca: "Riddara",  fecha: "2025-12-05" },
    { nombre: "Isabella",     apellido: "Silva",     email: "isabella.silva@gmail.com",       telefono: "+598 97 789 012", comentario: "Me gustaría recibir el catálogo completo del Citroën C3 y opciones de color.",           vehiculoNombreMarca: "Citroën",  fecha: "2025-12-10" },
    { nombre: "Nicolás",      apellido: "Díaz",      email: "ndiaz@empresa.com.uy",           telefono: "+598 99 890 123", comentario: "Soy empresa y necesito cotización para 3 unidades del Nissan Frontier.",                 vehiculoNombreMarca: "Nissan",   fecha: "2025-12-15" },
    { nombre: "Sofía",        apellido: "Torres",    email: "sofia.torres@gmail.com",         telefono: "+598 94 901 234", comentario: "Quiero comparar el BYD Atto 3 con el Peugeot e-2008. ¿Pueden asesorarme?",               vehiculoNombreMarca: "BYD",      fecha: "2025-12-19" },
    { nombre: "Andrés",       apellido: "Herrera",   email: "andresherrera85@gmail.com",      telefono: "+598 91 012 345", comentario: "¿El Renault Duster viene con tracción 4x4? Necesito para zona rural.",                  vehiculoNombreMarca: "Renault",  fecha: "2025-12-27" },

    // ── Enero 2026 ────────────────────────────────────────────────
    { nombre: "Martina",      apellido: "Morales",   email: "martina.morales@live.com",       telefono: "+598 98 111 222", comentario: "Vi la Riddara pickup en redes, ¿tienen versión de trabajo o solo recreativa?",           vehiculoNombreMarca: "Riddara",  fecha: "2026-01-07" },
    { nombre: "Facundo",      apellido: "Romero",    email: "facundo.romero@gmail.com",        telefono: "+598 95 222 333", comentario: "Me interesa el Citroën Berlingo para flete pequeño. ¿Tiene capacidad de carga?",        vehiculoNombreMarca: "Citroën",  fecha: "2026-01-10" },
    { nombre: "Paula",        apellido: "Jiménez",   email: "paulaj@hotmail.com",              telefono: "+598 93 333 444", comentario: "Busco el Peugeot 3008 usado certificado. ¿Tienen programa de seminuevos?",              vehiculoNombreMarca: "Peugeot",  fecha: "2026-01-14" },
    { nombre: "Emiliano",     apellido: "Vargas",    email: "evargas@gmail.com",               telefono: "+598 97 444 555", comentario: "¿El Subaru Outback incluye garantía extendida? Vivo en Maldonado.",                    vehiculoNombreMarca: "Subaru",   fecha: "2026-01-20" },
    { nombre: "Florencia",    apellido: "Castillo",  email: "flor.castillo@gmail.com",         telefono: "+598 99 555 666", comentario: "Soy primera compradora, ¿el BYD Seagull tiene financiamiento al 0% de interés?",       vehiculoNombreMarca: "BYD",      fecha: "2026-01-28" },
    { nombre: "Rodrigo",      apellido: "Núñez",     email: "rodrigonunez@gmail.com",           telefono: "+598 94 666 777", comentario: "¿Tienen el Nissan Note? Necesito algo compacto para la ciudad.",                     vehiculoNombreMarca: "Nissan",   fecha: "2026-01-31" },

    // ── Febrero 2026 ──────────────────────────────────────────────
    { nombre: "Jimena",       apellido: "Ramos",     email: "jimena.ramos@yahoo.com",          telefono: "+598 91 777 888", comentario: "Consulto por el Renault Kangoo para trabajo como delivery.",                           vehiculoNombreMarca: "Renault",  fecha: "2026-02-03" },
    { nombre: "Agustín",      apellido: "Reyes",     email: "agustin.reyes@gmail.com",          telefono: "+598 98 888 999", comentario: "¿El Citroën C5 Aircross está disponible en gris oscuro?",                            vehiculoNombreMarca: "Citroën",  fecha: "2026-02-06" },
    { nombre: "Natalia",      apellido: "Ortega",    email: "nataliaortega@gmail.com",          telefono: "+598 95 999 000", comentario: "Quiero permutar mi auto actual por el Peugeot 5008. ¿Hacen tasación sin cargo?",      vehiculoNombreMarca: "Peugeot",  fecha: "2026-02-11" },
    { nombre: "Maximiliano",  apellido: "Flores",    email: "maxiflores@gmail.com",             telefono: "+598 93 000 111", comentario: "¿La Riddara eléctrica tiene carga rápida? Viajo seguido a Rivera.",                  vehiculoNombreMarca: "Riddara",  fecha: "2026-02-14" },
    { nombre: "Carolina",     apellido: "Vega",      email: "carolina.vega@gmail.com",          telefono: "+598 94 112 233", comentario: "Busco el BYD Han, ¿tienen importación en camino?",                                   vehiculoNombreMarca: "BYD",      fecha: "2026-02-18" },
    { nombre: "Leandro",      apellido: "Castro",    email: "lcastro@outlook.com",              telefono: "+598 97 223 344", comentario: "¿El Nissan Murano viene en versión híbrida para Uruguay?",                           vehiculoNombreMarca: "Nissan",   fecha: "2026-02-24" },
    { nombre: "Verónica",     apellido: "Ibáñez",    email: "veroibanez@gmail.com",             telefono: "+598 99 334 455", comentario: "Mi empresa necesita 5 Subaru para vendedores. ¿Tienen precio corporativo?",           vehiculoNombreMarca: "Subaru",   fecha: "2026-02-27" },

    // ── Marzo 2026 ────────────────────────────────────────────────
    { nombre: "Gabriel",      apellido: "Mendoza",   email: "gmendoza@gmail.com",               telefono: "+598 91 445 566", comentario: "Necesito financiar el Renault Megane E-Tech. ¿Cuál es la cuota mensual?",             vehiculoNombreMarca: "Renault",  fecha: "2026-03-03" },
    { nombre: "Daniela",      apellido: "Sosa",      email: "danielasosa@live.com",             telefono: "+598 98 556 677", comentario: "¿El BYD Seal tiene entrega inmediata en Colonia?",                                    vehiculoNombreMarca: "BYD",      fecha: "2026-03-05" },
    { nombre: "Ramiro",       apellido: "Acosta",    email: "racosta@yahoo.com",                telefono: "+598 95 667 788", comentario: "Consulto por el Peugeot 408, ¿incluye garantía de por vida?",                        vehiculoNombreMarca: "Peugeot",  fecha: "2026-03-07" },
    { nombre: "Micaela",      apellido: "Ríos",      email: "mica.rios@gmail.com",              telefono: "+598 93 778 899", comentario: "¿La Riddara tiene concesionario en Montevideo? Vivo allá.",                           vehiculoNombreMarca: "Riddara",  fecha: "2026-03-10" },
    { nombre: "Ezequiel",     apellido: "Luna",      email: "ezequielluna@hotmail.com",         telefono: "+598 97 889 900", comentario: "Busco el Citroën ë-C3 100% eléctrico. ¿Cuándo llega a Uruguay?",                    vehiculoNombreMarca: "Citroën",  fecha: "2026-03-12" },
    { nombre: "Valeria",      apellido: "Suárez",    email: "valeria.suarez@gmail.com",         telefono: "+598 99 900 011", comentario: "Me interesa el Nissan X-Trail 3 filas. ¿Tienen usado?",                              vehiculoNombreMarca: "Nissan",   fecha: "2026-03-15" },
    { nombre: "Bruno",        apellido: "Paredes",   email: "bparedes@empresa.uy",              telefono: "+598 94 011 122", comentario: "Hola, quiero hacer un service del Subaru Forester 2022.",                             vehiculoNombreMarca: "Subaru",   fecha: "2026-03-18" },
    { nombre: "Mariana",      apellido: "Benítez",   email: "mbenitez@gmail.com",               telefono: "+598 91 122 233", comentario: "¿El Renault Austral tiene pantalla grande? Busco algo tecnológico.",                 vehiculoNombreMarca: "Renault",  fecha: "2026-03-21" },
    { nombre: "Sebastián",    apellido: "Quiroga",   email: "squiroga@gmail.com",               telefono: "+598 98 233 344", comentario: "Consulto por el BYD Dolphin Mini, ¿llega a Uruguay este año?",                      vehiculoNombreMarca: "BYD",      fecha: "2026-03-25" },
    { nombre: "Alejandra",    apellido: "Pinto",     email: "alejandra.pinto@live.com",         telefono: "+598 95 344 455", comentario: "¿Tienen el Peugeot Landtrek doble cabina? Busco para campo.",                       vehiculoNombreMarca: "Peugeot",  fecha: "2026-03-28" },

    // ── Abril 2026 ────────────────────────────────────────────────
    { nombre: "Ignacio",      apellido: "Salave",    email: "isalavegardia@gmail.com",          telefono: "+598 93 455 566", comentario: "Quiero el BYD Atto 3 blanco, ¿tienen en stock?",                                     vehiculoNombreMarca: "BYD",      fecha: "2026-04-01" },
    { nombre: "Macarena",     apellido: "Espinosa",  email: "mac.espinosa@outlook.com",         telefono: "+598 97 566 677", comentario: "Consulto por el Nissan Kicks e-Power. ¿Se puede con financiación?",                  vehiculoNombreMarca: "Nissan",   fecha: "2026-04-03" },
    { nombre: "Hernán",       apellido: "Delgado",   email: "hernandelgado@gmail.com",          telefono: "+598 99 677 788", comentario: "Vi una Riddara usada en la web, ¿sigue disponible?",                                  vehiculoNombreMarca: "Riddara",  fecha: "2026-04-07" },
    { nombre: "Paola",        apellido: "Ferraro",   email: "paola.ferraro@gmail.com",          telefono: "+598 94 788 899", comentario: "¿El Renault Clio tiene precio especial para jóvenes compradores?",                   vehiculoNombreMarca: "Renault",  fecha: "2026-04-09" },
    { nombre: "Cristian",     apellido: "Molina",    email: "cmolina@yahoo.com",                telefono: "+598 91 899 900", comentario: "Necesito un auto para Uber, ¿qué Citroën recomiendan para ese uso?",                 vehiculoNombreMarca: "Citroën",  fecha: "2026-04-11" },
    { nombre: "Tamara",       apellido: "Aguirre",   email: "tamara.aguirre@gmail.com",         telefono: "+598 98 900 011", comentario: "Hola, ¿tienen el Peugeot e-208 eléctrico en Colonia?",                               vehiculoNombreMarca: "Peugeot",  fecha: "2026-04-12" },
    { nombre: "Federico",     apellido: "Méndez",    email: "fmendez@hotmail.com",              telefono: "+598 95 011 122", comentario: "Busco financiación para el Subaru Crosstrek. Soy joven.",                             vehiculoNombreMarca: "Subaru",   fecha: "2026-04-14" },
    { nombre: "Lorena",       apellido: "Cabrera",   email: "lorena.cabrera@gmail.com",         telefono: "+598 93 122 233", comentario: "¿El BYD Tang tiene 7 asientos? Lo necesito para familia grande.",                    vehiculoNombreMarca: "BYD",      fecha: "2026-04-15" },
  ]
}

export default leads
